### ISSUE TITLE
Not able to show notebooks on Linux

### ISSUE THREAD

**Issue by HoWilgh** [spyder-ide/spyder-notebook#220] opened 2019-12-05 11:57 UTC
### What steps will reproduce the problem?

I simply opened a jupyter notebook with spyder and spyder-notebook installed.

- Selecting the notebook to open
- Tab is created in Spyder-notebook showing:
```
404 : Not Found
You are requesting a page that does not exist!
```
When trying to close the Tab a dialogue opens telling me that spyder encounterd an internal problem ... resulting in this issue-report

### Traceback
```python-traceback
  File "/home/user/bin/anaconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 387, in close_client
    client.shutdown_kernel()
  File "/home/user/bin/anaconda3/lib/python3.7/site-packages/spyder_notebook/widgets/client.py", line 255, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "/home/user/bin/anaconda3/lib/python3.7/site-packages/spyder_notebook/widgets/client.py", line 248, in get_kernel_id
    notebook_path = session.get('notebook', {}).get('path')
AttributeError: 'str' object has no attribute 'get'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-70-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.2.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.7 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.14 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.10.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment] 2019-12-05 20:00
This is probably an issue with your firewall. Are you able to open notebooks without problems using `jupyter notebook`?

**Comment by HoWilgh** [comment] 2019-12-06 07:34
No problems with jupyter notebook or jupyterlab on the same computer. No extra firewall installed (usual Ubuntu 16.04.x)
Have not used spyder notebook for several weeks now. Yesterday I updated everything via Anaconda and now it stopped working.

**Comment by HoWilgh** [comment] 2019-12-06 12:44
Anything else I can test?

**Comment by ccordoba12** [comment] 2020-01-07 03:14
Duplicate of #192

**Comment by ccordoba12** [comment] 2020-01-07 03:14
We don't know why this happens, sorry.

**Closed by ccordoba12** 2020-01-07 03:14 UTC
