### ISSUE TITLE
Not working with Spyder 4.1.5 (via Anaconda3-2020.11)

### ISSUE THREAD

**Issue by boardtc** [spyder-ide/spyder-notebook#363] opened 2021-05-17 14:21 UTC
## Not working with Spyder 4.1.5 (via Anaconda3-2020.11)

**What steps will reproduce the problem?**

1. Install Anaconda3-2020.11-Windows-x86_64.exe
2. Open command prompt and type: conda install spyder-notebook -c spyder-ide
3. Open Spyder and then open a .ipynb
4. It just shows as if spyder-notebook was not installed, just a json file

## Versions and main components

* Spyder Version: 4.1.5
* Python Version: 3.7.3
* Operating system: Windows 10

## Dependencies

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)

# Spyder plugins:
spyder_notebook                :  0.3.2 (OK)
spyder_unittest                :  0.4.1 (OK)

**Comment by salmanea** [comment] 2021-05-19 10:45
Same here.
Not working with Spyder 5
![image](https://user-images.githubusercontent.com/7900672/118800331-11551980-b8a0-11eb-85c6-bc7b0afbaa02.png)

**Comment by mmagnuski** [comment] 2021-07-05 13:38
related: #362, #360

**Comment by ccordoba12** [comment] 2022-09-05 14:03
Right, closing as a duplicate of those issues.

**Closed by ccordoba12** 2022-09-05 14:03 UTC
