### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by AZdet** [spyder-ide/spyder-notebook#120] opened 2017-10-12 15:13 UTC
I install it with "conda install spyder-notebook -c spyder-ide", and my OS is windows 10 Education, and spyder is 3.2.3 and my notebook is 5.0.0. After finishing installation, I find when I open spyder it stops at setting up main window. Then I uninstall the plugin and spyder is working again.
  I'd appreciate any help.

**Comment by dalthviz** [comment] 2017-10-12 18:11
Hi @AZdet when you running do you see any message or Spyder simply stops setting up the mainwindow and closes?

**Comment by AZdet** [comment] 2017-10-13 03:53
no messages, just stop at the "setting up the main window" stage. When I try to click at the window, Windows says that this program has no resonance and I can either wait or close the program.

**Comment by dalthviz** [comment] 2017-10-13 05:14
Could you run spyder from `cmd` with `--show-console` and see if any output is shown and post it here?

**Comment by AZdet** [comment] 2017-10-13 06:42
![image](https://user-images.githubusercontent.com/28669500/31533420-b2e5671a-b024-11e7-9ab3-e585bafb5962.png)
no, nothing is posted...

**Comment by AZdet** [comment] 2017-10-13 06:44
<img width="595" alt="2017-10-13_14-40-54" src="https://user-images.githubusercontent.com/28669500/31533470-f83c1c64-b024-11e7-9ea7-4e9d6e58bd2a.png">

**Comment by dalthviz** [comment] 2017-10-21 19:41
Hi again @AZdet if you run the notebook server in a different cmd (with the command `jupyter notebook`), and then try to open Spyder with the spyder-notebook installed, anything changes?

**Comment by AZdet** [comment] 2017-10-23 08:55
No, still nothing is shown in the cmd console of Spyder. The Jupyter notebook is working as normal though.

**Comment by dalthviz** [comment] 2017-10-26 04:56
And do you have some other plugins installed @AZdet?

**Comment by AZdet** [comment] 2017-10-26 16:36
I am afraid not. This is my first plugin in my Spyder IDE.

**Comment by dalthviz** [comment] 2017-10-26 17:54
Could you please provide us the list of dependencies in your conda env?, to try to create the same environment in our end.

**Comment by akrsrivastava** [comment] 2017-11-11 10:14
I have a similar problem on Windows 10. I installed with "conda install spyder-notebook -c spyder-ide" . But I dont see any options to create a pynb file. I would have expected to see an option for ipynb when I do Ctrl+N, but this just creates a new .py file.

**Comment by dalthviz** [comment] 2017-11-11 16:47
Hi @akrsrivastava please, could you provide the specs of your system and the list of packages in your environment? Also, if you are using conda, could you create a new env with only Spyder and the plugin and try it again? All the info you could provide will be greatly appreciated.

About the understanding of the use is something we are thinking how to improve and some ideas are in #39, if you have some other ideas let us know :)

**Comment by akrsrivastava** [comment] 2017-11-11 18:57
@dalthviz Its a fresh Anaconda install, so only the default Anaconda packages are there, nothing more. I am on Windows 10, 8 GB RAM, i5 with Nvidia 4GB 640MX GPU. I did try on a fresh conda env, but had the same issue there as well.

**Comment by ccordoba12** [comment] 2017-11-11 19:33
@akrsrivastava, please post a screenshot about what you're seeing.

**Comment by akrsrivastava** [comment] 2017-11-11 19:42
![spyder](https://user-images.githubusercontent.com/19535249/32692875-29bacb54-c746-11e7-8e35-25f820358248.JPG)

This pane is not editable. I cant left click on this pane. I can only right click on it which brings up the context menu.

**Comment by AZdet** [comment] 2017-11-12 04:10
Sorry, I replied to you directly @Daniel Althviz Moré  and you may not see the email. Thanks for helping me out.  Here is my conda list in the attachment conda_list.txt

[conda_list.txt](https://github.com/spyder-ide/spyder-notebook/files/1464365/conda_list.txt)

 

I didn’t install jupyterlab when I had the problem with Spyder notebook.

 

 I know how hard and painful to debug. Thanks again for helping me out! Good luck debugging.

 

Best,

Alex

**Comment by AZdet** [comment] 2017-11-12 07:24
Hi, today I tried to uninstall the plugin and update Spyder from 3.2.3 to 3.2.4 and reinstall the plugin. When I started Spyder again, though it still didn't work, but it gave one prompt I had not seen before. 
![spyder_error](https://user-images.githubusercontent.com/28669500/32696790-4b579fd2-c7bc-11e7-86ed-48eddbbee135.png)

Also I checked my Jupyter notebook. When I started jupyter notebook in cmd, I saw 
![spyder_error2](https://user-images.githubusercontent.com/28669500/32696805-aa2b1e9e-c7bc-11e7-8efd-9692a81150b2.png)

I found for some reasons my port 8888 is taken. Maybe this is the cause of my problem.  How can I fix it?

**Comment by AZdet** [comment] 2017-11-12 07:27
Hi, today I tried to uninstall the plugin and update Spyder from 3.2.3 to 3.2.4 and reinstall the plugin. When I started Spyder again, though it still didn't work, but it gave one prompt I had not seen before. 
![spyder_error](https://user-images.githubusercontent.com/28669500/32696790-4b579fd2-c7bc-11e7-86ed-48eddbbee135.png)

Also I checked my Jupyter notebook. When I started jupyter notebook in cmd, I saw 
![spyder_error2](https://user-images.githubusercontent.com/28669500/32696805-aa2b1e9e-c7bc-11e7-8efd-9692a81150b2.png)

I found for some reasons my port 8888 is taken. Maybe this is the cause of my problem.  How can I fix it?

**Comment by AZdet** [comment] 2017-11-12 10:27
Oh I realized that port 8888 was actually taken by Spyder. And I tried to start Spyder several times, but it stopped at "setting up the main window" without any prompt just like before.

**Comment by dalthviz** [comment] 2017-11-12 17:27
Thanks for the feedback @AZdet @akrsrivastava :+1:. Maybe this is related with #113. Could you guys see if changing the range following the instructions in #113 helps?

**Comment by AZdet** [comment] 2017-11-13 03:08
Unfortunately, it didn't work for me. What's more, I was unable to reproduce the situation with that the prompt after I tried to uninstall the plugin, spyder and notebook and install them again.

**Comment by akrsrivastava** [comment] 2017-11-13 07:21
Some further troubleshooting:

I am unable to create a new Notebook from within Spyder. But once I start Jupyter Notebook from the Anaconda prompt, I am able to create a new notebook from within Spyder. Not sure if that's how it is supposed to work.

However I am facing another error when trying to close the notebooks which I create without starting Jupyter notebook  

![notebooks](https://user-images.githubusercontent.com/19535249/32713774-c5a7f2f0-c870-11e7-8f97-931ac83b48b6.JPG)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 222, in get_kernel_id
    sessions = json.loads(sessions_req)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


So now I am left with a set of notebooks which I can not close unless I restart Spyder.

**Comment by dalthviz** [comment] 2017-11-16 18:37
Thanks for the testing @AZdet and @akrsrivastava :+1: 

In your case @AZdet, could you try to first start the notebook server (make sure you don't have Spyder open) and then start Spyder?

About the case of @akrsrivastava, @ccordoba12 should we add a try for the `shutdown_kernel` method to let work the plugin even if the Notebook server is started outside Spyder? Maybe this could be an alternative if starting the server with Spyder takes a lot of time?

**Comment by AZdet** [comment] 2017-11-20 03:23
I tried to first start notebook server, but my problem remained. It just stopped at the "setting up the main window" endlessly.

**Comment by JTD2017** [comment] 2018-08-01 22:50
Im having the same problem, I can't left click anything, it's like it's frozen but I can still right click normally. This is really strange as it started happening all of a sudden...

**Comment by Xabitsuki** [comment] 2018-10-11 12:06
Hi I have the same problem of spider displaying a blank not editable page. Spyder threw the following message : 

[I 14:01:26.265 NotebookApp] JupyterLab beta preview extension loaded from /Users/…./anaconda3/lib/python3.6/site-packages/jupyterlab 
[I 14:01:26.265 NotebookApp] JupyterLab application directory is /Users/…../anaconda3/share/jupyter/lab 
[I 14:01:26.272 NotebookApp] Serving notebooks from local directory: /var/folders/nc/59_0s6cx2n582_ct3x1j5tn40000gn/T/spyder-……/notebooks 
[I 14:01:26.272 NotebookApp] 0 active kernels 
[I 14:01:26.272 NotebookApp] The Jupyter Notebook is running at:
 [I 14:01:26.272 NotebookApp] http://localhost:8888/token=ef35d78f74b64d308419eeb74497657c122eaf2a45b7cdae
 [I 14:01:26.272 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation). 
[C 14:01:26.272 NotebookApp]   

Copy/paste this URL into your browser when you connect for the first time, to login with a token: http://localhost:8888/?token=ef35d78f74b64d308419eeb74497657c122eaf2a45b7cdae
 js: Uncaught TypeError: Cannot set property 'className' of null
 js: Uncaught TypeError: Cannot set property 'className' of null
 js: Uncaught TypeError: Cannot set property 'className' of null 
js: WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
 js: Uncaught TypeError: Cannot set property 'className' of null 
js: Uncaught ReferenceError: Invalid left-hand side in assignment

**Comment by mmagnuski** [comment] 2018-10-20 20:31
@dalthviz
I've had the same problem as @akrsrivastava on a couple on windows computers (some classroom computers and some students' laptops, about 4 machines total). I'll try separate env on those machines or reinstalling spyder-notebook in a few days and I will let you know.

**Comment by ccordoba12** [comment] 2018-10-20 23:11
@mmagnuski, this plugin is still in a bit of beta state, so I wouldn't recommend to use it for classes or something.

**Comment by mmagnuski** [comment] 2018-10-21 18:34
> That will come in Spyder 4.

That's wonderful!
I was wondering today how I could help with that because I saw that the issue on notebook - varexp sync is without any updates. I even spent some time today looking through jupyter/ipykernel docs and code to see how one could check or attach to a hook to be informed when notebook finished processing. But as I am not familiar with the internals of jupyter/ipykernel I didn't find much. My understanding is that you now know how to detect / be informed of these events, right?

**Comment by ccordoba12** [comment] 2018-10-21 21:44
We need to rewrite the way we detect when a computation is finished. That's why this needs to be done in Spyder 4 and it's not a simple fix.

**Comment by mmagnuski** [comment] 2018-11-17 11:05
@ccordoba12 I fixed problems on most (maybe all) classroom machines that had problems running spyder-notebook. This was usually a matter of updating dependencies. One or two machines did not have updated spyder, another two did not have updated nbconvert (IIRC). I still have some students reporting problems on their notebooks, but for at least two the problem seemed to just spontaneously disappear.

**Comment by partha1968** [comment] 2020-01-16 15:44
I am using Ananconda 64 bit in Windows.I have installed Spyder 4.0.1 and I have installed Spyder 4.0.1 and also installeed spyder -notebook 0.2.1.  But I can see that spyder notebook is not present in interface. How to start Python notebook and start working ?

**Comment by jitseniesen** [comment] 2020-01-16 16:08
@partha1968 Can you open notebooks using Jupyter? Does the `View | Panes` menu in Spyder have an entry called "Notebook"?

**Comment by partha1968** [comment] 2020-01-16 16:18
I can open notebooks using Jupyter.Yes  there is " Notebook" . I have started it. Thanks

**Comment by jitseniesen** [comment] 2020-07-30 20:33
This is all about version 0.1 of the plugin, we never managed to reproduce it and we have just released version 0.3, so I am closing this issue. If anybody encounters the same problem with version 0.3, please open a new issue so that we can get to the bottom of it.

**Closed by jitseniesen** 2020-07-30 20:33 UTC
