### ISSUE TITLE
Cannot use spyder-notebook, get error on trying to create a new notebook

### ISSUE THREAD

**Issue by momih** [spyder-ide/spyder-notebook#116] opened 2017-10-04 16:07 UTC
## Description

**What steps will reproduce the problem?**

1. `conda install spyder-notebook -c spyder-ide`
2. Open Spyder, then go to Notebook tab
3. Right-click and select either New Notebook or Open

**What is the expected output? What do you see instead?**
Expected output would be a notebook in Spyder. But I get this dialog box instead
![screenshot from 2017-10-04 12-03-55](https://user-images.githubusercontent.com/22825943/31186259-21e4ba06-a8fc-11e7-96bd-8fe29ada7db5.png)

**Please provide any additional information below**

```
  File "/home/momi/anaconda2/lib/python2.7/site-packages/spyder_notebook/notebookplugin.py", line 314, in create_new_client
    server_info = nbopen(filename)
  File "/home/momi/anaconda2/lib/python2.7/site-packages/spyder_notebook/utils/nbopen.py", line 75, in nbopen
    proc = subprocess.Popen(command, creationflags=creation_flag)
  File "/home/momi/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/momi/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux
* Jupyter Notebook Version: 4.3.0
## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by dalthviz** [comment] 2017-10-05 02:02
Hi @momih what happens if you run the notebook server from a terminal? Are you able to start it normally?

**Comment by momih** [comment] 2017-10-05 14:54
@dalthviz Yes it works from a terminal

**Comment by dalthviz** [comment] 2017-10-05 15:09
@momih are you using a custom-launcher for Spyder? if you run Spyder from a terminal what happens?

**Comment by momih** [comment] 2017-10-08 20:10
Yes I can open a notebook if I launch Spyder through the terminal but not if I click on the icon in the launcher.

**Comment by dalthviz** [comment] 2017-10-09 01:53
Thanks for your response @momih, then this is a duplicate of #106. Please, if you get more info, post it there.

**Closed by dalthviz** 2017-10-09 01:53 UTC
