### ISSUE TITLE
Which versions of everything are needed to get this thing to work...

### ISSUE THREAD

**Issue by dkinneyBU** [spyder-ide/spyder-notebook#374] opened 2022-05-13 17:43 UTC
I get that spyder notebook does not work with spyder 5 and we have no ETA as to when that will happen, so what versions of everything do I need to actually get this to work?

Python?
Spyder?
Anything else?

I've tried Python 3.8 with Spyder 4.2.5 and 4.1 and I still just get a blank screen in the Notebook window. It doesn't bring up an error just a White Screen of Death.

I realize this is not actually an issue, but I didn't know how else to get your attention to get my question answered.

thanks
Dave K.

**Comment by ccordoba12** [comment] 2022-05-15 16:50
Hey @dkinneyBU, thanks for reporting. At this point I think it's really hard to make this package work with an older Spyder 4 version because a lot of things have changed since our last version in that series (4.2.5) was released last year.

Therefore, I think you'll have to be patient and wait until we release a version that is compatible with Spyder 5. I'll try to do that in the next couple of months.

**Comment by ccordoba12** [comment] 2022-05-15 16:50
For now I'm going to close this issue as a duplicate of #360.

**Closed by ccordoba12** 2022-05-15 16:50 UTC

**Comment by dkinneyBU** [comment] 2022-05-15 20:01
@ccordoba12  All good on closing; I'll keep an eye out for the 5-compatible version. Thank you for the quick reply, much appreciated.
