### ISSUE TITLE
In Ubuntu can not view the autocompletion suggestion text in notebook pane

### ISSUE THREAD

**Issue by rohan-paul** [spyder-ide/spyder-notebook#327] opened 2020-10-25 11:16 UTC
### Problem Description

When I press tab to bring up the autocompletion suggestions, the text of the suggestions are not viewable, in almost all of the dark themes, in notebook pane (.ipynb file).

The text of the suggestions, get merged into the dark background of the dark themes. And while in the light theme, its slightly better, but there also not fully and clearly visible.

But the suggestion text, is working just fine in the Editor pane (.py file).

Screenshot below.

![image](https://user-images.githubusercontent.com/12703975/97105511-3bb36f80-16e1-11eb-8234-d2e7d74d7f62.png)

## Versions

* Spyder version: 4.1.5 None
* Python version: 3.7.6 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-52-generic

**Comment by jitseniesen** [comment] 2020-10-27 20:18
Thanks for the report. This is a duplicate of #318 which we hope to fix soon; please follow that issue if you want to be kept informed.

**Closed by jitseniesen** 2020-10-27 20:18 UTC
