### ISSUE TITLE
open a notebook in a course of Coursera fail

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder-notebook#126] opened 2017-10-17 12:59 UTC
## Description of your problem
https://hub.coursera-notebooks.org/user/yhzinmxbfrtvazsoinzcyf/notebooks/week7/Tensorflow%20Tutorial.ipynb
the link is the notebook. 
it work fine in chrome, but it fail to open in spyder-notebook v0.1.1

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Qt Version: unknown
* PyQt Version: 5.9
* Jupyter Notebook Version: 5.0.0
* Operating system: windows 7

**Comment by ccordoba12** [comment] 2017-10-17 16:49
How does it fail to open? I mean, are you seeing an error message when you try to open the notebook?

**Comment by adaaaaaa** [comment] 2017-10-18 09:39
no any error message...and then the spyder become no response...i have to kill it in the task manager...
@ccordoba12

**Comment by adaaaaaa** [comment] 2017-10-18 09:41
any other notebook in my local disk work fine...
but this online notebook i can not open it...

**Comment by ccordoba12** [comment] 2017-10-18 13:56
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment] 2017-10-18 21:40
Hi @adaaaaaa could you please provide the notebook that you can't open?. The url of coursera needs credentials to access it:

![imagen](https://user-images.githubusercontent.com/16781833/31743884-60b1db20-b422-11e7-8d83-40cffaf7bec7.png)

Also, when you are trying to open the notebook, it's in your local disk?

**Comment by adaaaaaa** [comment] 2017-10-19 01:40
no , i open it in Spyder with the url, not in my local disk...

[Tensorflow+Tutorial.zip](https://github.com/spyder-ide/spyder-notebook/files/1396826/Tensorflow.Tutorial.zip)

**Comment by dalthviz** [comment] 2017-10-19 18:54
Try opening the notebook from a local version in your disk. It should open:

![imagen](https://user-images.githubusercontent.com/16781833/31788239-c8a4fa80-b4d3-11e7-8dd7-2b551ea5fd24.png)

I think the issue here was a misunderstanding of the current capabilities of the plugin. It only can open notebooks in your file system (notebooks that are already in your local disk).

**Comment by adaaaaaa** [comment] 2017-10-20 00:49
can it open a online notebook in the future?

**Comment by dalthviz** [comment] 2017-10-20 01:15
I think this could be related with #81, @ccordoba12 what do you think?

**Comment by ccordoba12** [comment] 2017-10-20 14:06
Yep, it's true. Let's close this one as a duplicate of issue #81.

**Closed by ccordoba12** 2017-10-20 14:06 UTC
