### ISSUE TITLE
Creation of blank tabs after upgrading to spyder 3.2.1

### ISSUE THREAD

**Issue by ronimb** [spyder-ide/spyder-notebook#111] opened 2017-08-17 08:17 UTC
After upgrading to spyder 3.2.1, 
it appears the notebook plugin no longer works,
no error messages are displayed, however attempting to create a new notebook or open an existing notebook results in the creation of a new tab with no content whatsoever.
These are the packages that were updated during the upgrade:

2017-08-17 11:09:31  (rev 8)
     icu  {57.1 -> 58.1 (conda-forge)}
     libpng  {1.6.27 -> 1.6.28 (conda-forge)}
     pyqt  {5.6.0 -> 5.6.0 (conda-forge)}
     qt  {5.6.2 -> 5.6.2 (conda-forge)}
    +vc-14 (conda-forge)

2017-08-17 11:10:14  (rev 9)
     spyder  {3.2.0 -> 3.2.1 (conda-forge)}

**Comment by ccordoba12** [comment] 2017-08-17 13:55
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment] 2017-08-17 18:37
Hi @ronimb what was the command that you used to update spyder?. Also what is your OS? I made the update in Windows but no problem arise

**Comment by ronimb** [comment] 2017-08-17 19:21
This happened on a windows7 machine,
I updated using:
conda update qt pyqt
conda update spyder

As per the recommended instructions,
Haven't tested this on my home pc, i can try to replicate the issue there on if it helps

**Comment by dalthviz** [comment] 2017-08-17 23:35
Please try to replicate it, all the info will be greatly appreciated, thanks!

**Comment by ronimb** [comment] 2017-08-20 14:20
So i ran the update on my home computer (a windows 10 machine).
And everything still works fine, must be something with the lab machine in particular,
I've tried downgrading back to spyder 3.2, but the problem persists

**Comment by andfoy** [comment] 2017-08-20 14:58
It seems that conda-forge packages were used during the update

**Comment by ronimb** [comment] 2017-08-20 15:04
Yes, that is also the case with my home pc

**Comment by dalthviz** [comment] 2017-08-20 15:10
@ronimb can you put here the package list of the env that you have in the lab machine? Maybe could you try to create another env in the machine where you are facing this problem? Also, what was the command you used to install the plugin?

**Comment by ronimb** [comment] 2017-08-20 15:14
Sure, i'll post the list here tomorrow and see what happens with a new environment.
As for installing the plugin,
There's a spyder-notebook package in the conda-forge channel, so i simply used
conda install spyder-notebook 
on both my home machine and the lab pc

**Comment by ronimb** [comment] 2017-08-21 05:42
I've attached the file with packages installed in the default environment,
ill get to creating a test environment later on

[ronimb_lab_pkgs.txt](https://github.com/spyder-ide/spyder-notebook/files/1237880/ronimb_lab_pkgs.txt)

**Comment by ronimb** [comment] 2017-08-21 06:00
Well...
everything seems to work fine in the new test environment (lab computer),
i'm attaching the package listing for test environment as well so you can have a look and compare.

[ronimb_lab_pkgs_testenv.txt](https://github.com/spyder-ide/spyder-notebook/files/1237906/ronimb_lab_pkgs_testenv.txt)

**Comment by ronimb** [comment] 2017-08-21 06:04
Ok,
so for some reason everything is now working correctly even on the main environment,
can't say what i did other than create the new test environment, but i don't really see why that would affect the main env....

**Comment by dalthviz** [comment] 2017-08-21 15:12
Thats weird, but it's great to know that now everything works as expected. The only difference I see between the envs you provide (besides some packages) is that in the new env the packages are mostly from conda-forge. Let us know if you find out the root cause, and thanks for the testing and the info!

**Comment by tribbloid** [comment] 2017-08-26 00:04
This happens on Ubuntu 17.04 when launching a notebook in spyder 3.2.1:

Server Error

The Jupyter Notebook server failed to start or it is taking too much time to do it. Please start it in a system terminal with the command 'jupyter notebook' to check for errors.

**Comment by dalthviz** [comment] 2017-08-26 00:33
Hi @tribbloid, the message you are seeing happens, as the message say, when the notebook server is taking too much time to start or failes to start. Are you also seeing blank tabs as this issue states?

If not you can try to open a new notebook this should try to initialize again the server. If this didn't help, try to run the command `jupyter notebook` in a terminal an see if any errors arise.

**Comment by dalthviz** [comment] 2017-09-07 19:30
@ccordoba12 should we close this one?

**Comment by tribbloid** [comment] 2017-09-08 02:26
@dalthviz don't close! when I use command 'jupyter notebook' in command line everything loads as usual. Except 1 submodule which gave the following error information:

```
$ jupyter notebook
[I 22:22:29.277 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 22:22:29.587 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'
[I 22:22:29.589 NotebookApp] Serving notebooks from local directory: /home/peng
[I 22:22:29.589 NotebookApp] 0 active kernels 
[I 22:22:29.589 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=66a66ffa792ce2cce5bbdc902ad6756d721f9c02e4110d59
[I 22:22:29.589 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:22:29.590 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=66a66ffa792ce2cce5bbdc902ad6756d721f9c02e4110d59
[I 22:22:29.873 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[6311:6349:0907/222229.885466:ERROR:nss_util.cc(747)] After loading Root Certs, loaded==false: NSS error code: -8018
[6311:6349:0907/222229.886232:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.

```

This should only be a minor submodule error and should not impede plugin's ability to communicate with it.

**Comment by dalthviz** [comment] 2017-09-08 03:33
Hi @tribbloid it seems that the problem you're facing is different from the one of @ronimb. Also, how much is taking for you to start the server?. Maybe we can change the time the plugin waits for the server to start (we wait with [this code](https://github.com/spyder-ide/spyder-notebook/blob/master/spyder_notebook/utils/nbopen.py#L88)). 

Since the initial problem of @ronimb  was 'resolved' I'm closing this issue, however we will keep track of your problem, so please open a new issue with all the info you can provide us (it's just for the sake of having issues properly described and organized)  :)

**Closed by dalthviz** 2017-09-08 03:33 UTC
Labels: type:Bug
