### ISSUE TITLE
Error when closing a file that has been deleted externally.

### ISSUE THREAD

**Issue by ForeverAnApple** [spyder-ide/spyder-notebook#195] opened 2019-01-19 00:27 UTC
### What steps will reproduce the problem?

1. Open a file in spyder.
2. Delete the file outside of spyder.
3. Try to close the buffer of the deleted file.

### Traceback
```python-traceback
  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 374, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/home/user/anaconda3/lib/python3.7/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/[path to file]'
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.20.3-arch1-1-ARCH

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment] 2019-01-19 08:45
Closing as a duplicate of #194.

**Closed by ccordoba12** 2019-01-19 08:45 UTC
