### ISSUE TITLE
Anaconda update to 1.10.0 seems to break notebook plugin

### ISSUE THREAD

**Issue by jeremyharbinson** [spyder-ide/spyder-notebook#350] opened 2021-01-05 16:24 UTC
## Description of your problem
I am running Anaconda 1.10.0, Notebook 6.1.6, Spyder 4.0.1 on macOS 10.15.7 (still using BASH) - more details below.  

I have just updated to 1.10.0 and prior to this Spyder would run the notebook plugin just fine now it does not. 

Updating Anaconda was a problem so I used 'update conda --all', after which I could not start Spyder - I got the following error: 
'/Users/jeremyharbinson1/opt/anaconda3/bin/pythonw: line 3: /Users/jeremyharbinson1/opt/anaconda3/python.app/Contents/MacOS/python: No such file or directory'. 

This was solved by running ' conda install -f python.app'. 

After this Spyder would start but with the error: 
"[C 16:37:24.021 NotebookApp] Bad config encountered during initialization: The 'kernel_spec_class' trait of <jupyter_client.kernelspec.KernelSpecManager object at 0x7fe3ac012250> instance must be a type, but "'spyder.plugins.ipythonconsole.utils.kernelspec.SpyderKernelSpec'" could not be imported"

Spyder will then start but no notebook can be started.

I can run 'jupyter notebook', get the notebook dashboard, open a notebook and execute commands with no problems.

**What steps will reproduce the problem?**

1. enter 'spyder', press return
2. 
3. 

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**
error message details are above.

## Versions and main components

* Spyder Version: 4.0.1
* Python Version:3.7.9
* Qt Version:5.12.9
* PyQt Version: 5.12.3
* Jupyter Notebook Version:6.1.6
* Operating system: macOS 10.15.7
* spyder-kernels: 1.8.1
* spyder-notebook: 0.2.3

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment] 2021-01-05 17:16
Thanks for your report. This is probably caused by an incompatibility with the traitlets library. You need to upgrade spyder-notebook to version 0.3.1 (which will also upgrade Spyder). The command for this is `conda install -c spyder-ide spyder-notebook=0.3.1`. An alternative is to downgrade traitlets to version 4. 

Please see issue spyder-ide/spyder-notebook#314 for more information. I'm closing this as a duplicate of that issue.

**Closed by jitseniesen** 2021-01-05 17:16 UTC
