### ISSUE TITLE
Installed with conda, but wont start Segmentation fault

### ISSUE THREAD

**Issue by Goddard** [spyder-ide/spyder-notebook#136] opened 2017-11-21 02:08 UTC
## Description of your problem

**What steps will reproduce the problem?**

1.  install with conda-forge 3.6

## Versions and main components
    spyder:          3.2.4-py36_0 conda-forge
    spyder-notebook: 0.1.1-py36_0 spyder-ide 

* Operating system: Ubuntu 16.04

**Comment by dalthviz** [comment] 2017-11-21 04:32
Hi @Goddard, did you start Spyder from a terminal or from a custom-launcher?, did you do something more than installing it with conda-forge? any info in order to reproduce the issue will be greatly appreciated

**Comment by Goddard** [comment] 2017-11-21 14:43
I was just trying to launch it from the terminal.  No I only tried conda forge.  Let me know if you want me to test anything else.

**Comment by dalthviz** [comment] 2017-11-21 18:13
Some things that maybe could help here: try to uninstall the plugin and see if the segmentation fault doesn't appears (just to be sure the plugin causes the segfault and Spyder it self runs just fine without it). Also, could you provide us the list of packages in the conda env you saw this behavior? Finally, could you try to create a new env only with Spyder and the plugin installed and see if the segfault persists there?

Thanks @Goddard :)

**Comment by jitseniesen** [comment] 2018-08-22 13:40
Closing due to lack of follow-up

**Closed by jitseniesen** 2018-08-22 13:40 UTC
