### ISSUE TITLE
Spyder-Notebook never shows up in Spyder View... Panes menu

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder-notebook#362] opened 2021-04-28 04:39 UTC
## Description of your problem

**What steps will reproduce the problem?**

I have installed Spyder using WinPython 3.9.4 (latest version as of today)   

I then installed Spyder-Notebook using conda from the command line. 

1. install using "conda install spyder-notebook" into environment with Spyder 4.2.1 or Spyder 5.0.1
2. Spyder-Notebook never shows up on the menu system under Views. 
3. 

**What is the expected output? What do you see instead?**

Spyder-Notebook never shows up on the menu system under Views.
Spyder-Notebook never appears as a tabbed window next to the Spyder Main Editor

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

It shows up as being installed in the iPython console inside Spyder v5.0.1:
```

!conda list spyder-notebook
>> packages in environment at c:\ProgramData\Anaconda3:
>>
>> Name                    Version                   Build  Channel
spyder-notebook           0.1.4                      py_0    conda-forge

```
## Versions and main components

* Spyder Version:  5.0.1
* Python Version: Python 3.9.4
* Qt Version:   5.15.1  
* PyQt Version:  PyQt5 5.15.1 
* Jupyter Notebook Version:
* Operating system:  Windows 10 Professional

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.10.0.dev0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by jitseniesen** [comment] 2021-04-28 19:58
The Spyder notebook plugin is not yet compatible with Spyder 5 (this is tracked in issue #360). The latest version of spyder-notebook is compatible with Spyder 4.2, but the output of `conda list` shows that you have version 0.1.4 of spyder-notebook installed and that is not the latest version. You need at least version 0.3; the current version is 0.3.2.

**Comment by Mathanraj-Sharma** [comment] 2021-04-29 18:33
@jitseniesen when we can expect a release of the supported version for spyder=5.0.1

**Comment by mmagnuski** [comment] 2021-07-05 13:14
@jitseniesen I think this is the version of spyder-notebook that is installed by default via `conda install spyder-notebook -c spyder-ide` when Spyder 5 is installed. I had one student with the exact same scenario - installing spyder notebook with Spyder 5 installed version 0.1.4. Downgrading to Spyder 4 upgraded spyder-notebook to 0.3.2.

**Comment by barthhsk** [comment] 2022-09-04 22:13
@ccordoba12 This issue seems not resolved by closing issue #360

**Comment by ccordoba12** [comment] 2022-09-05 14:02
A new version gas not been released yet. Please be patient.

I'm going to close this issue as a duplicate of issue #360.

**Closed by ccordoba12** 2022-09-05 14:02 UTC

**Comment by batiyilmaz** [comment] 2024-04-03 18:48
Is it available for Spyder 5.5.3 now?

**Comment by ccordoba12** [comment] 2024-04-03 20:54
Yes, it is. Please check out the Readme of this project to learn how to install it.

**Comment by batiyilmaz** [comment] 2024-04-03 21:20
I have tried to install it by referring to the Readme today, however, I cannot find it in panes and in dependencies as well.

**Comment by ccordoba12** [comment] 2024-04-03 21:29
Are you using our Windows or macOS standalone installer?

**Comment by batiyilmaz** [comment] 2024-04-26 05:15
> Are you using our Windows or macOS standalone installer?

I have used a macOS standalone installer via the Spyder website.

**Comment by ccordoba12** [comment] 2024-04-26 17:19
That's what I thought. In case it's not possible to use this plugin because our installers are completely self-contained (i.e. they can't be modified).

So, you need to install Spyder-Notebook from Conda-forge, as described in our Readme.
